Sheer_knowlegebase_index:
    pattern: /knowlegebase
    defaults: { _controller: Sheer.knowlegebase.controller.index:main }
Sheer_knowlegebase_category:
    pattern: /knowlegebase/category
    defaults: { _controller: Sheer.knowlegebase.controller.category:cat }
Sheer_knowlegebase_article:
    pattern: /knowlegebase/article
    defaults: { _controller: Sheer.knowlegebase.controller.article:show }
Sheer_knowlegebase_edit:
    pattern: /knowlegebase/edit
    defaults: { _controller: Sheer.knowlegebase.controller.edit:edit_article }
Sheer_knowlegebase_post:
    pattern: /knowlegebase/post
    defaults: { _controller: Sheer.knowlegebase.controller.post:post_article }

Sheer_knowlegebase_library_search:
    pattern: /knowlegebase/library_search
    defaults: { _controller: Sheer.knowlegebase.controller.library_search:main }

Sheer_knowlegebase_approve:
    pattern: /knowlegebase/approve
    defaults: { _controller: Sheer.knowlegebase.controller.approve:approve_article }
