services:
    sheer.knowlegebase.controller.index:
        class: sheer\knowlegebase\controller\index
        arguments:
            - @config
            - @request
            - @pagination
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @sheer.knowlegebase.inc

    sheer.knowlegebase.controller.category:
        class: sheer\knowlegebase\controller\category
        arguments:
            - @config
            - @request
            - @pagination
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @sheer.knowlegebase.inc

    sheer.knowlegebase.controller.article:
        class: sheer\knowlegebase\controller\article
        arguments:
            - @config
            - @request
            - @dbal.conn
            - @auth
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @sheer.knowlegebase.inc

    sheer.knowlegebase.controller.edit:
        class: sheer\knowlegebase\controller\edit
        arguments:
            - @config
            - @request
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache
            - @log
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @sheer.knowlegebase.inc

    sheer.knowlegebase.controller.post:
        class: sheer\knowlegebase\controller\post
        arguments:
            - @config
            - @request
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache
            - @log
            - @notification_manager
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @sheer.knowlegebase.inc
            - @sheer.knowlegebase.helper

    sheer.knowlegebase.controller.library_search:
        class: sheer\knowlegebase\controller\library_search
        arguments:
            - @config
            - @request
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache
            - @pagination
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @sheer.knowlegebase.inc

    sheer.knowlegebase.controller.approve:
        class: sheer\knowlegebase\controller\approve
        arguments:
            - @config
            - @request
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache
            - @log
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @sheer.knowlegebase.inc
            - @sheer.knowlegebase.helper

    sheer.knowlegebase.listener:
        class: sheer\knowlegebase\event\listener
        arguments:
            - @template
            - @user
            - %core.root_path%
        tags:
            - { name: event.listener }

    sheer.knowlegebase.inc:
        class: sheer\knowlegebase\inc\functions_kb
        arguments:
            - @config
            - @dbal.conn
            - @cache
            - @user
            - @template
            - @auth
            - @log
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%

    sheer.knowlegebase.helper:
        class: sheer\knowlegebase\core\helper
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - @cache.driver
            - @request
            - @notification_manager
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%

    sheer.knowlegebase.notification.type.need_approval:
        class: sheer\knowlegebase\notification\need_approval
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    sheer.knowlegebase.notification.type.approve:
        class: sheer\knowlegebase\notification\approve
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    sheer.knowlegebase.notification.type.disapprove:
        class: sheer\knowlegebase\notification\disapprove
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }
